name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        package_manager: [npm, yarn]
        package_root: ["./test/app-in-root/"]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install test app dependencies
        run: |
          cd ${{ matrix.package_root }}
          ${{ matrix.package_manager }} install

      - name: Run action
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          package_root: ${{ matrix.package_root }}
          use_vue_cli: ${{ contains(matrix.package_root, 'vue')}}
          max_attempts: "2"
